2020-02-10T17:01:28,291 Non-user install because user site-packages disabled
2020-02-10T17:01:28,307 Created temporary directory: /tmp/pip-ephem-wheel-cache-_mm9ryq8
2020-02-10T17:01:28,307 Created temporary directory: /tmp/pip-req-tracker-9e50yxkr
2020-02-10T17:01:28,307 Initialized build tracking at /tmp/pip-req-tracker-9e50yxkr
2020-02-10T17:01:28,307 Created build tracker: /tmp/pip-req-tracker-9e50yxkr
2020-02-10T17:01:28,307 Entered build tracker: /tmp/pip-req-tracker-9e50yxkr
2020-02-10T17:01:28,307 Created temporary directory: /tmp/pip-install-xp1w4vov
2020-02-10T17:01:28,308 Obtaining file:///root/projects/pgbackup
2020-02-10T17:01:28,308   Added file:///root/projects/pgbackup to build tracker '/tmp/pip-req-tracker-9e50yxkr'
2020-02-10T17:01:28,308     Running setup.py (path:/root/projects/pgbackup/setup.py) egg_info for package from file:///root/projects/pgbackup
2020-02-10T17:01:28,308     Running command python setup.py egg_info
2020-02-10T17:01:28,520     Traceback (most recent call last):
2020-02-10T17:01:28,521       File "<string>", line 1, in <module>
2020-02-10T17:01:28,521       File "/root/projects/pgbackup/setup.py", line 16
2020-02-10T17:01:28,521         package_dir={'': 'src'},
2020-02-10T17:01:28,521                   ^
2020-02-10T17:01:28,521     SyntaxError: invalid syntax
2020-02-10T17:01:28,534 Cleaning up...
2020-02-10T17:01:28,535 Removed file:///root/projects/pgbackup from build tracker '/tmp/pip-req-tracker-9e50yxkr'
2020-02-10T17:01:28,535 Removed build tracker: '/tmp/pip-req-tracker-9e50yxkr'
2020-02-10T17:01:28,535 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-02-10T17:01:28,535 Exception information:
2020-02-10T17:01:28,535 Traceback (most recent call last):
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
2020-02-10T17:01:28,535     status = self.run(options, args)
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
2020-02-10T17:01:28,535     resolver.resolve(requirement_set)
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
2020-02-10T17:01:28,535     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
2020-02-10T17:01:28,535     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 265, in _get_abstract_dist_for
2020-02-10T17:01:28,535     return self.preparer.prepare_editable_requirement(req)
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 555, in prepare_editable_requirement
2020-02-10T17:01:28,535     req, self.req_tracker, self.finder, self.build_isolation,
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
2020-02-10T17:01:28,535     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
2020-02-10T17:01:28,535     self.req.prepare_metadata()
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 564, in prepare_metadata
2020-02-10T17:01:28,535     self.metadata_directory = self._generate_metadata()
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 544, in _generate_metadata
2020-02-10T17:01:28,535     details=self.name or "from {}".format(self.link)
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 118, in generate_metadata
2020-02-10T17:01:28,535     command_desc='python setup.py egg_info',
2020-02-10T17:01:28,535   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2020-02-10T17:01:28,535     raise InstallationError(exc_msg)
2020-02-10T17:01:28,535 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-02-10T17:04:28,990 Non-user install because user site-packages disabled
2020-02-10T17:04:29,004 Created temporary directory: /tmp/pip-ephem-wheel-cache-muk4olbl
2020-02-10T17:04:29,005 Created temporary directory: /tmp/pip-req-tracker-jqdmu9or
2020-02-10T17:04:29,005 Initialized build tracking at /tmp/pip-req-tracker-jqdmu9or
2020-02-10T17:04:29,005 Created build tracker: /tmp/pip-req-tracker-jqdmu9or
2020-02-10T17:04:29,005 Entered build tracker: /tmp/pip-req-tracker-jqdmu9or
2020-02-10T17:04:29,005 Created temporary directory: /tmp/pip-install-cqx0cw5e
2020-02-10T17:04:29,006 Obtaining file:///root/projects/pgbackup
2020-02-10T17:04:29,006   Added file:///root/projects/pgbackup to build tracker '/tmp/pip-req-tracker-jqdmu9or'
2020-02-10T17:04:29,006     Running setup.py (path:/root/projects/pgbackup/setup.py) egg_info for package from file:///root/projects/pgbackup
2020-02-10T17:04:29,006     Running command python setup.py egg_info
2020-02-10T17:04:29,223     Traceback (most recent call last):
2020-02-10T17:04:29,223       File "<string>", line 1, in <module>
2020-02-10T17:04:29,223       File "/root/projects/pgbackup/setup.py", line 16
2020-02-10T17:04:29,223         package_dir={'': 'src'},
2020-02-10T17:04:29,223                   ^
2020-02-10T17:04:29,223     SyntaxError: invalid syntax
2020-02-10T17:04:29,237 Cleaning up...
2020-02-10T17:04:29,238 Removed file:///root/projects/pgbackup from build tracker '/tmp/pip-req-tracker-jqdmu9or'
2020-02-10T17:04:29,238 Removed build tracker: '/tmp/pip-req-tracker-jqdmu9or'
2020-02-10T17:04:29,238 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-02-10T17:04:29,238 Exception information:
2020-02-10T17:04:29,238 Traceback (most recent call last):
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
2020-02-10T17:04:29,238     status = self.run(options, args)
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
2020-02-10T17:04:29,238     resolver.resolve(requirement_set)
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
2020-02-10T17:04:29,238     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
2020-02-10T17:04:29,238     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 265, in _get_abstract_dist_for
2020-02-10T17:04:29,238     return self.preparer.prepare_editable_requirement(req)
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 555, in prepare_editable_requirement
2020-02-10T17:04:29,238     req, self.req_tracker, self.finder, self.build_isolation,
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
2020-02-10T17:04:29,238     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
2020-02-10T17:04:29,238     self.req.prepare_metadata()
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 564, in prepare_metadata
2020-02-10T17:04:29,238     self.metadata_directory = self._generate_metadata()
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 544, in _generate_metadata
2020-02-10T17:04:29,238     details=self.name or "from {}".format(self.link)
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 118, in generate_metadata
2020-02-10T17:04:29,238     command_desc='python setup.py egg_info',
2020-02-10T17:04:29,238   File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2020-02-10T17:04:29,238     raise InstallationError(exc_msg)
2020-02-10T17:04:29,238 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
